travis:
  secure:
    BINSTAR_TOKEN: xHOpPG7a2gCqT25hqLvt6mThE8VMCRJWIYFIeVa5Wm3gNWekyWc/Vy8NLk+iMh1tNFidKwhLGgx0B2hmFF+BCXeXTSgme+ZVw+C89jaNZEfVQO4tzy6Vj49YroZtiUgJT+xWvCOPK7i4dXV2ZbyvshowsDA0qRHrq2N1vnu7WXq5l/bP+PVvl1vm8OXHPrSKXjELZI5D1UmscrInlOdp1KS+vnAuF9zDn6pltzNAK93K9Sqobu2pqYYLLRliqZvWRi19l+lVhMTEPuUp3nckBHV9hOl3k6754cnYz5zecBCO2yck6RDvRzCOpxeH+OC6ERTl+Mvf/An97j/PyWnD6JLyY9IeUN1l0eGOpZzeWppYDhgCleUL75sqYIFtAKsw2eHrI0BsKpT7WJK7YmVG07QHfdzhPbKY2fg8abJTrh6faNw3W8TkrA9VRNv1iBanGlvC3zuqlTzprl5qCZG2YN2jl2vRCqFo9ICOWDeTEqKbvqLe0DPkF+wfuCUwTuTn2+jHZTRDsIY7UblzZMXVZH1bpFFZ8TS3IZXLsNFR9XOhigy1FswaLkjpzoI1WeElfNA4dUaMekmRiSrH+LwaBRHMkB3A67i3dSWO4Hb5P8yQchTb3ZbSzpeKmBDPeAHaarMtrxSLICAew+zIoSerQAhLGze52N15s0EDI0V5keI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
