travis:
  secure:
    BINSTAR_TOKEN: W4pnMyQ8wCQ9maKiQ9vIKTWk4LuIfPZ8DeKrqX8Bd5+9ZF6F5AL0aDGQuXabsRqbeGv9kq71Q89q9BcBXc5rIazsP3QF4UFIVaY9FNkh/B54HVDMDM1rH1ER5DBFp/EaIn33BfnIEB2ozz314UAyA2jHAYbbRCnWIYjiFAS2aXxs0u0NhuLHytWWMwYtNsKiTxTa+vwiKB2Pr2cHoercHEeD4DniOr/hbIvxkFkXrTRhU7shj44a3f+5vkbemZ5mBzdls4yyUWZyiK+QzPCCJ40CnaFntoRk7o9FLjWmxaWrJszz+xtZ09ccZCABjzHeO0hW5s48WfI/ybnkQR9WYXjoMB+tmkfDiD1PutWOzyfqte9gJB+rn/0DGD0UszWasusYtU1tTeEZY9vqsim0Ml+kQjfMzCrqkS1fWyExR0Yt1UwgmCnoP4rvgMQK84oI5i7xLGAHsAGUJeDaUfA+XfdxSktEW8WY1AQfHnfb5Jar7fg6/1t8dGoitOzKiCmY/miUfltu7zt5LXLVSMwRKm9CtNVSXufstCqB39QVM+iofZK7lUurvW/3EJwbvY9d1aNdK1R6zmas9t3nmf9cVh3FBin7JFkUcOzwSwU9h27ma842bKhjhtFRvzzxQBlWE/k7qlJq8zp9yU+AkxT6s7tlt2NoGY8+10rkN0Y+hL4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
